[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "alloc", "compiler_builtins"]

[build]
target = "riscv32ima-unknown-none-elf"

[target.riscv32ima-unknown-none-elf]
rustflags = ["-C", "link-arg=rvem_layout.ld"]
